/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewMarksRouteImport } from './routes/view-marks'
import { Route as TeacherProfileRouteImport } from './routes/teacher-profile'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentDashboardRouteImport } from './routes/student-dashboard'
import { Route as StudentRouteImport } from './routes/student'
import { Route as StaffRegistrationRouteImport } from './routes/staff-registration'
import { Route as StaffLoginRouteImport } from './routes/staff-login'
import { Route as StaffDashboardRouteImport } from './routes/staff-dashboard'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as RegisterParentRouteImport } from './routes/register-parent'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginStudentRouteImport } from './routes/login-student'
import { Route as LoginStaffRouteImport } from './routes/login-staff'
import { Route as LoginParentRouteImport } from './routes/login-parent'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FilterPageRouteImport } from './routes/filter-page'
import { Route as DisciplineMasterRouteImport } from './routes/discipline-master'
import { Route as DescriptionRouteImport } from './routes/description'
import { Route as DashboardWithSidebarRouteImport } from './routes/dashboard-with-sidebar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as DisciplineMasterIndexRouteImport } from './routes/discipline-master.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherReportsRouteImport } from './routes/teacher.reports'
import { Route as TeacherMessagesRouteImport } from './routes/teacher.messages'
import { Route as TeacherMaterialsRouteImport } from './routes/teacher.materials'
import { Route as TeacherMarksRouteImport } from './routes/teacher.marks'
import { Route as TeacherLiveRouteImport } from './routes/teacher.live'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as StudentScheduleRouteImport } from './routes/student.schedule'
import { Route as StudentQuizRouteImport } from './routes/student.quiz'
import { Route as StudentMaterialsRouteImport } from './routes/student.materials'
import { Route as StudentLiveRouteImport } from './routes/student.live'
import { Route as StudentGradesRouteImport } from './routes/student.grades'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as ParentReportsRouteImport } from './routes/parent.reports'
import { Route as ParentPerformanceRouteImport } from './routes/parent.performance'
import { Route as ParentNotificationsRouteImport } from './routes/parent.notifications'
import { Route as ParentMessagesRouteImport } from './routes/parent.messages'
import { Route as ParentDisciplineRouteImport } from './routes/parent.discipline'
import { Route as ParentChildrenRouteImport } from './routes/parent.children'
import { Route as ParentAttendanceRouteImport } from './routes/parent.attendance'
import { Route as ParentAcademicRouteImport } from './routes/parent.academic'
import { Route as DisciplineMasterStudentsRouteImport } from './routes/discipline-master.students'
import { Route as DisciplineMasterSettingsRouteImport } from './routes/discipline-master.settings'
import { Route as DisciplineMasterReportsRouteImport } from './routes/discipline-master.reports'
import { Route as DisciplineMasterPermissionRouteImport } from './routes/discipline-master.permission'
import { Route as DisciplineMasterNotificationsRouteImport } from './routes/discipline-master.notifications'
import { Route as DisciplineMasterMessagesRouteImport } from './routes/discipline-master.messages'
import { Route as DisciplineMasterDisciplineRouteImport } from './routes/discipline-master.discipline'
import { Route as DisciplineMasterDeductMarksRouteImport } from './routes/discipline-master.deduct-marks'
import { Route as DisciplineMasterCasesRouteImport } from './routes/discipline-master.cases'
import { Route as DisciplineMasterAttendanceRouteImport } from './routes/discipline-master.attendance'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTimetableRouteImport } from './routes/admin.timetable'
import { Route as AdminTermManagementRouteImport } from './routes/admin.term-management'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminTeacherProfileRouteImport } from './routes/admin.teacher-profile'
import { Route as AdminTeacherInfoRouteImport } from './routes/admin.teacher-info'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminStudentDisciplineRouteImport } from './routes/admin.student-discipline'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSendNotificationRouteImport } from './routes/admin.send-notification'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPreviousTermsRouteImport } from './routes/admin.previous-terms'
import { Route as AdminParentRequestsRouteImport } from './routes/admin.parent-requests'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminManageCoursesRouteImport } from './routes/admin.manage-courses'
import { Route as AdminManageAcademicsRouteImport } from './routes/admin.manage-academics'
import { Route as AdminEditTeacherRouteImport } from './routes/admin.edit-teacher'
import { Route as AdminDeductMarksRouteImport } from './routes/admin.deduct-marks'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAssignClassesRouteImport } from './routes/admin.assign-classes'
import { Route as AdminAddTeacherRouteImport } from './routes/admin.add-teacher'
import { Route as AdminAddStudentRouteImport } from './routes/admin.add-student'
import { Route as AdminAcademicsBackupRouteImport } from './routes/admin.academics-backup'
import { Route as AdminAcademicsRouteImport } from './routes/admin.academics'
import { Route as DisciplineMasterDeductMarksTestRouteImport } from './routes/discipline-master.deduct-marks.test'
import { Route as DisciplineMasterDeductMarksIdRouteImport } from './routes/discipline-master.deduct-marks.$id'
import { Route as AdminUsersTeacherRouteImport } from './routes/admin.users.teacher'
import { Route as AdminTeachersIdRouteImport } from './routes/admin/teachers/$id'

const ViewMarksRoute = ViewMarksRouteImport.update({
  id: '/view-marks',
  path: '/view-marks',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/teacher-profile',
  path: '/teacher-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student-dashboard',
  path: '/student-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRegistrationRoute = StaffRegistrationRouteImport.update({
  id: '/staff-registration',
  path: '/staff-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff-login',
  path: '/staff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/staff-dashboard',
  path: '/staff-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterParentRoute = RegisterParentRouteImport.update({
  id: '/register-parent',
  path: '/register-parent',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginStudentRoute = LoginStudentRouteImport.update({
  id: '/login-student',
  path: '/login-student',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginStaffRoute = LoginStaffRouteImport.update({
  id: '/login-staff',
  path: '/login-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginParentRoute = LoginParentRouteImport.update({
  id: '/login-parent',
  path: '/login-parent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FilterPageRoute = FilterPageRouteImport.update({
  id: '/filter-page',
  path: '/filter-page',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplineMasterRoute = DisciplineMasterRouteImport.update({
  id: '/discipline-master',
  path: '/discipline-master',
  getParentRoute: () => rootRouteImport,
} as any)
const DescriptionRoute = DescriptionRouteImport.update({
  id: '/description',
  path: '/description',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWithSidebarRoute = DashboardWithSidebarRouteImport.update({
  id: '/dashboard-with-sidebar',
  path: '/dashboard-with-sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const DisciplineMasterIndexRoute = DisciplineMasterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DisciplineMasterRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMessagesRoute = TeacherMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMaterialsRoute = TeacherMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMarksRoute = TeacherMarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherLiveRoute = TeacherLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentScheduleRoute = StudentScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => StudentRoute,
} as any)
const StudentQuizRoute = StudentQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMaterialsRoute = StudentMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLiveRoute = StudentLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => StudentRoute,
} as any)
const StudentGradesRoute = StudentGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const ParentReportsRoute = ParentReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ParentRoute,
} as any)
const ParentPerformanceRoute = ParentPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => ParentRoute,
} as any)
const ParentNotificationsRoute = ParentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ParentRoute,
} as any)
const ParentMessagesRoute = ParentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ParentRoute,
} as any)
const ParentDisciplineRoute = ParentDisciplineRouteImport.update({
  id: '/discipline',
  path: '/discipline',
  getParentRoute: () => ParentRoute,
} as any)
const ParentChildrenRoute = ParentChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => ParentRoute,
} as any)
const ParentAttendanceRoute = ParentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => ParentRoute,
} as any)
const ParentAcademicRoute = ParentAcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => ParentRoute,
} as any)
const DisciplineMasterStudentsRoute =
  DisciplineMasterStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => DisciplineMasterRoute,
  } as any)
const DisciplineMasterSettingsRoute =
  DisciplineMasterSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DisciplineMasterRoute,
  } as any)
const DisciplineMasterReportsRoute = DisciplineMasterReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DisciplineMasterRoute,
} as any)
const DisciplineMasterPermissionRoute =
  DisciplineMasterPermissionRouteImport.update({
    id: '/permission',
    path: '/permission',
    getParentRoute: () => DisciplineMasterRoute,
  } as any)
const DisciplineMasterNotificationsRoute =
  DisciplineMasterNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DisciplineMasterRoute,
  } as any)
const DisciplineMasterMessagesRoute =
  DisciplineMasterMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => DisciplineMasterRoute,
  } as any)
const DisciplineMasterDisciplineRoute =
  DisciplineMasterDisciplineRouteImport.update({
    id: '/discipline',
    path: '/discipline',
    getParentRoute: () => DisciplineMasterRoute,
  } as any)
const DisciplineMasterDeductMarksRoute =
  DisciplineMasterDeductMarksRouteImport.update({
    id: '/deduct-marks',
    path: '/deduct-marks',
    getParentRoute: () => DisciplineMasterRoute,
  } as any)
const DisciplineMasterCasesRoute = DisciplineMasterCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => DisciplineMasterRoute,
} as any)
const DisciplineMasterAttendanceRoute =
  DisciplineMasterAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => DisciplineMasterRoute,
  } as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTimetableRoute = AdminTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTermManagementRoute = AdminTermManagementRouteImport.update({
  id: '/term-management',
  path: '/term-management',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeacherProfileRoute = AdminTeacherProfileRouteImport.update({
  id: '/teacher-profile',
  path: '/teacher-profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeacherInfoRoute = AdminTeacherInfoRouteImport.update({
  id: '/teacher-info',
  path: '/teacher-info',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentDisciplineRoute = AdminStudentDisciplineRouteImport.update({
  id: '/student-discipline',
  path: '/student-discipline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSendNotificationRoute = AdminSendNotificationRouteImport.update({
  id: '/send-notification',
  path: '/send-notification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreviousTermsRoute = AdminPreviousTermsRouteImport.update({
  id: '/previous-terms',
  path: '/previous-terms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParentRequestsRoute = AdminParentRequestsRouteImport.update({
  id: '/parent-requests',
  path: '/parent-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManageCoursesRoute = AdminManageCoursesRouteImport.update({
  id: '/manage-courses',
  path: '/manage-courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManageAcademicsRoute = AdminManageAcademicsRouteImport.update({
  id: '/manage-academics',
  path: '/manage-academics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditTeacherRoute = AdminEditTeacherRouteImport.update({
  id: '/edit-teacher',
  path: '/edit-teacher',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeductMarksRoute = AdminDeductMarksRouteImport.update({
  id: '/deduct-marks',
  path: '/deduct-marks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssignClassesRoute = AdminAssignClassesRouteImport.update({
  id: '/assign-classes',
  path: '/assign-classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAddTeacherRoute = AdminAddTeacherRouteImport.update({
  id: '/add-teacher',
  path: '/add-teacher',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAddStudentRoute = AdminAddStudentRouteImport.update({
  id: '/add-student',
  path: '/add-student',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademicsBackupRoute = AdminAcademicsBackupRouteImport.update({
  id: '/academics-backup',
  path: '/academics-backup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademicsRoute = AdminAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => AdminRoute,
} as any)
const DisciplineMasterDeductMarksTestRoute =
  DisciplineMasterDeductMarksTestRouteImport.update({
    id: '/test',
    path: '/test',
    getParentRoute: () => DisciplineMasterDeductMarksRoute,
  } as any)
const DisciplineMasterDeductMarksIdRoute =
  DisciplineMasterDeductMarksIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DisciplineMasterDeductMarksRoute,
  } as any)
const AdminUsersTeacherRoute = AdminUsersTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminTeachersIdRoute = AdminTeachersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTeachersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard-with-sidebar': typeof DashboardWithSidebarRoute
  '/description': typeof DescriptionRoute
  '/discipline-master': typeof DisciplineMasterRouteWithChildren
  '/filter-page': typeof FilterPageRoute
  '/login': typeof LoginRoute
  '/login-parent': typeof LoginParentRoute
  '/login-staff': typeof LoginStaffRoute
  '/login-student': typeof LoginStudentRoute
  '/maintenance': typeof MaintenanceRoute
  '/parent': typeof ParentRouteWithChildren
  '/register-parent': typeof RegisterParentRoute
  '/registration': typeof RegistrationRoute
  '/setup': typeof SetupRoute
  '/staff-dashboard': typeof StaffDashboardRoute
  '/staff-login': typeof StaffLoginRoute
  '/staff-registration': typeof StaffRegistrationRoute
  '/student': typeof StudentRouteWithChildren
  '/student-dashboard': typeof StudentDashboardRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/teacher-profile': typeof TeacherProfileRoute
  '/view-marks': typeof ViewMarksRoute
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/academics-backup': typeof AdminAcademicsBackupRoute
  '/admin/add-student': typeof AdminAddStudentRoute
  '/admin/add-teacher': typeof AdminAddTeacherRoute
  '/admin/assign-classes': typeof AdminAssignClassesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/deduct-marks': typeof AdminDeductMarksRoute
  '/admin/edit-teacher': typeof AdminEditTeacherRoute
  '/admin/manage-academics': typeof AdminManageAcademicsRoute
  '/admin/manage-courses': typeof AdminManageCoursesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parent-requests': typeof AdminParentRequestsRoute
  '/admin/previous-terms': typeof AdminPreviousTermsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/send-notification': typeof AdminSendNotificationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/student-discipline': typeof AdminStudentDisciplineRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teacher-info': typeof AdminTeacherInfoRoute
  '/admin/teacher-profile': typeof AdminTeacherProfileRoute
  '/admin/teachers': typeof AdminTeachersRouteWithChildren
  '/admin/term-management': typeof AdminTermManagementRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/discipline-master/attendance': typeof DisciplineMasterAttendanceRoute
  '/discipline-master/cases': typeof DisciplineMasterCasesRoute
  '/discipline-master/deduct-marks': typeof DisciplineMasterDeductMarksRouteWithChildren
  '/discipline-master/discipline': typeof DisciplineMasterDisciplineRoute
  '/discipline-master/messages': typeof DisciplineMasterMessagesRoute
  '/discipline-master/notifications': typeof DisciplineMasterNotificationsRoute
  '/discipline-master/permission': typeof DisciplineMasterPermissionRoute
  '/discipline-master/reports': typeof DisciplineMasterReportsRoute
  '/discipline-master/settings': typeof DisciplineMasterSettingsRoute
  '/discipline-master/students': typeof DisciplineMasterStudentsRoute
  '/parent/academic': typeof ParentAcademicRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/discipline': typeof ParentDisciplineRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/performance': typeof ParentPerformanceRoute
  '/parent/reports': typeof ParentReportsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/live': typeof StudentLiveRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/quiz': typeof StudentQuizRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/live': typeof TeacherLiveRoute
  '/teacher/marks': typeof TeacherMarksRoute
  '/teacher/materials': typeof TeacherMaterialsRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/discipline-master/': typeof DisciplineMasterIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/teachers/$id': typeof AdminTeachersIdRoute
  '/admin/users/teacher': typeof AdminUsersTeacherRoute
  '/discipline-master/deduct-marks/$id': typeof DisciplineMasterDeductMarksIdRoute
  '/discipline-master/deduct-marks/test': typeof DisciplineMasterDeductMarksTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard-with-sidebar': typeof DashboardWithSidebarRoute
  '/description': typeof DescriptionRoute
  '/filter-page': typeof FilterPageRoute
  '/login': typeof LoginRoute
  '/login-parent': typeof LoginParentRoute
  '/login-staff': typeof LoginStaffRoute
  '/login-student': typeof LoginStudentRoute
  '/maintenance': typeof MaintenanceRoute
  '/register-parent': typeof RegisterParentRoute
  '/registration': typeof RegistrationRoute
  '/setup': typeof SetupRoute
  '/staff-dashboard': typeof StaffDashboardRoute
  '/staff-login': typeof StaffLoginRoute
  '/staff-registration': typeof StaffRegistrationRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/teacher-profile': typeof TeacherProfileRoute
  '/view-marks': typeof ViewMarksRoute
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/academics-backup': typeof AdminAcademicsBackupRoute
  '/admin/add-student': typeof AdminAddStudentRoute
  '/admin/add-teacher': typeof AdminAddTeacherRoute
  '/admin/assign-classes': typeof AdminAssignClassesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/deduct-marks': typeof AdminDeductMarksRoute
  '/admin/edit-teacher': typeof AdminEditTeacherRoute
  '/admin/manage-academics': typeof AdminManageAcademicsRoute
  '/admin/manage-courses': typeof AdminManageCoursesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parent-requests': typeof AdminParentRequestsRoute
  '/admin/previous-terms': typeof AdminPreviousTermsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/send-notification': typeof AdminSendNotificationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/student-discipline': typeof AdminStudentDisciplineRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teacher-info': typeof AdminTeacherInfoRoute
  '/admin/teacher-profile': typeof AdminTeacherProfileRoute
  '/admin/teachers': typeof AdminTeachersRouteWithChildren
  '/admin/term-management': typeof AdminTermManagementRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/discipline-master/attendance': typeof DisciplineMasterAttendanceRoute
  '/discipline-master/cases': typeof DisciplineMasterCasesRoute
  '/discipline-master/deduct-marks': typeof DisciplineMasterDeductMarksRouteWithChildren
  '/discipline-master/discipline': typeof DisciplineMasterDisciplineRoute
  '/discipline-master/messages': typeof DisciplineMasterMessagesRoute
  '/discipline-master/notifications': typeof DisciplineMasterNotificationsRoute
  '/discipline-master/permission': typeof DisciplineMasterPermissionRoute
  '/discipline-master/reports': typeof DisciplineMasterReportsRoute
  '/discipline-master/settings': typeof DisciplineMasterSettingsRoute
  '/discipline-master/students': typeof DisciplineMasterStudentsRoute
  '/parent/academic': typeof ParentAcademicRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/discipline': typeof ParentDisciplineRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/performance': typeof ParentPerformanceRoute
  '/parent/reports': typeof ParentReportsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/live': typeof StudentLiveRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/quiz': typeof StudentQuizRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/live': typeof TeacherLiveRoute
  '/teacher/marks': typeof TeacherMarksRoute
  '/teacher/materials': typeof TeacherMaterialsRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/admin': typeof AdminIndexRoute
  '/discipline-master': typeof DisciplineMasterIndexRoute
  '/parent': typeof ParentIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/admin/teachers/$id': typeof AdminTeachersIdRoute
  '/admin/users/teacher': typeof AdminUsersTeacherRoute
  '/discipline-master/deduct-marks/$id': typeof DisciplineMasterDeductMarksIdRoute
  '/discipline-master/deduct-marks/test': typeof DisciplineMasterDeductMarksTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard-with-sidebar': typeof DashboardWithSidebarRoute
  '/description': typeof DescriptionRoute
  '/discipline-master': typeof DisciplineMasterRouteWithChildren
  '/filter-page': typeof FilterPageRoute
  '/login': typeof LoginRoute
  '/login-parent': typeof LoginParentRoute
  '/login-staff': typeof LoginStaffRoute
  '/login-student': typeof LoginStudentRoute
  '/maintenance': typeof MaintenanceRoute
  '/parent': typeof ParentRouteWithChildren
  '/register-parent': typeof RegisterParentRoute
  '/registration': typeof RegistrationRoute
  '/setup': typeof SetupRoute
  '/staff-dashboard': typeof StaffDashboardRoute
  '/staff-login': typeof StaffLoginRoute
  '/staff-registration': typeof StaffRegistrationRoute
  '/student': typeof StudentRouteWithChildren
  '/student-dashboard': typeof StudentDashboardRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/teacher-profile': typeof TeacherProfileRoute
  '/view-marks': typeof ViewMarksRoute
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/academics-backup': typeof AdminAcademicsBackupRoute
  '/admin/add-student': typeof AdminAddStudentRoute
  '/admin/add-teacher': typeof AdminAddTeacherRoute
  '/admin/assign-classes': typeof AdminAssignClassesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/deduct-marks': typeof AdminDeductMarksRoute
  '/admin/edit-teacher': typeof AdminEditTeacherRoute
  '/admin/manage-academics': typeof AdminManageAcademicsRoute
  '/admin/manage-courses': typeof AdminManageCoursesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parent-requests': typeof AdminParentRequestsRoute
  '/admin/previous-terms': typeof AdminPreviousTermsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/send-notification': typeof AdminSendNotificationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/student-discipline': typeof AdminStudentDisciplineRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teacher-info': typeof AdminTeacherInfoRoute
  '/admin/teacher-profile': typeof AdminTeacherProfileRoute
  '/admin/teachers': typeof AdminTeachersRouteWithChildren
  '/admin/term-management': typeof AdminTermManagementRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/discipline-master/attendance': typeof DisciplineMasterAttendanceRoute
  '/discipline-master/cases': typeof DisciplineMasterCasesRoute
  '/discipline-master/deduct-marks': typeof DisciplineMasterDeductMarksRouteWithChildren
  '/discipline-master/discipline': typeof DisciplineMasterDisciplineRoute
  '/discipline-master/messages': typeof DisciplineMasterMessagesRoute
  '/discipline-master/notifications': typeof DisciplineMasterNotificationsRoute
  '/discipline-master/permission': typeof DisciplineMasterPermissionRoute
  '/discipline-master/reports': typeof DisciplineMasterReportsRoute
  '/discipline-master/settings': typeof DisciplineMasterSettingsRoute
  '/discipline-master/students': typeof DisciplineMasterStudentsRoute
  '/parent/academic': typeof ParentAcademicRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/discipline': typeof ParentDisciplineRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/performance': typeof ParentPerformanceRoute
  '/parent/reports': typeof ParentReportsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/live': typeof StudentLiveRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/quiz': typeof StudentQuizRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/live': typeof TeacherLiveRoute
  '/teacher/marks': typeof TeacherMarksRoute
  '/teacher/materials': typeof TeacherMaterialsRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/discipline-master/': typeof DisciplineMasterIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/teachers/$id': typeof AdminTeachersIdRoute
  '/admin/users/teacher': typeof AdminUsersTeacherRoute
  '/discipline-master/deduct-marks/$id': typeof DisciplineMasterDeductMarksIdRoute
  '/discipline-master/deduct-marks/test': typeof DisciplineMasterDeductMarksTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard-with-sidebar'
    | '/description'
    | '/discipline-master'
    | '/filter-page'
    | '/login'
    | '/login-parent'
    | '/login-staff'
    | '/login-student'
    | '/maintenance'
    | '/parent'
    | '/register-parent'
    | '/registration'
    | '/setup'
    | '/staff-dashboard'
    | '/staff-login'
    | '/staff-registration'
    | '/student'
    | '/student-dashboard'
    | '/teacher'
    | '/teacher-profile'
    | '/view-marks'
    | '/admin/academics'
    | '/admin/academics-backup'
    | '/admin/add-student'
    | '/admin/add-teacher'
    | '/admin/assign-classes'
    | '/admin/audit'
    | '/admin/deduct-marks'
    | '/admin/edit-teacher'
    | '/admin/manage-academics'
    | '/admin/manage-courses'
    | '/admin/notifications'
    | '/admin/parent-requests'
    | '/admin/previous-terms'
    | '/admin/reports'
    | '/admin/reset-password'
    | '/admin/send-notification'
    | '/admin/settings'
    | '/admin/student-discipline'
    | '/admin/students'
    | '/admin/teacher-info'
    | '/admin/teacher-profile'
    | '/admin/teachers'
    | '/admin/term-management'
    | '/admin/timetable'
    | '/admin/users'
    | '/discipline-master/attendance'
    | '/discipline-master/cases'
    | '/discipline-master/deduct-marks'
    | '/discipline-master/discipline'
    | '/discipline-master/messages'
    | '/discipline-master/notifications'
    | '/discipline-master/permission'
    | '/discipline-master/reports'
    | '/discipline-master/settings'
    | '/discipline-master/students'
    | '/parent/academic'
    | '/parent/attendance'
    | '/parent/children'
    | '/parent/discipline'
    | '/parent/messages'
    | '/parent/notifications'
    | '/parent/performance'
    | '/parent/reports'
    | '/student/attendance'
    | '/student/grades'
    | '/student/live'
    | '/student/materials'
    | '/student/quiz'
    | '/student/schedule'
    | '/teacher/attendance'
    | '/teacher/live'
    | '/teacher/marks'
    | '/teacher/materials'
    | '/teacher/messages'
    | '/teacher/reports'
    | '/admin/'
    | '/discipline-master/'
    | '/parent/'
    | '/student/'
    | '/teacher/'
    | '/admin/teachers/$id'
    | '/admin/users/teacher'
    | '/discipline-master/deduct-marks/$id'
    | '/discipline-master/deduct-marks/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard-with-sidebar'
    | '/description'
    | '/filter-page'
    | '/login'
    | '/login-parent'
    | '/login-staff'
    | '/login-student'
    | '/maintenance'
    | '/register-parent'
    | '/registration'
    | '/setup'
    | '/staff-dashboard'
    | '/staff-login'
    | '/staff-registration'
    | '/student-dashboard'
    | '/teacher-profile'
    | '/view-marks'
    | '/admin/academics'
    | '/admin/academics-backup'
    | '/admin/add-student'
    | '/admin/add-teacher'
    | '/admin/assign-classes'
    | '/admin/audit'
    | '/admin/deduct-marks'
    | '/admin/edit-teacher'
    | '/admin/manage-academics'
    | '/admin/manage-courses'
    | '/admin/notifications'
    | '/admin/parent-requests'
    | '/admin/previous-terms'
    | '/admin/reports'
    | '/admin/reset-password'
    | '/admin/send-notification'
    | '/admin/settings'
    | '/admin/student-discipline'
    | '/admin/students'
    | '/admin/teacher-info'
    | '/admin/teacher-profile'
    | '/admin/teachers'
    | '/admin/term-management'
    | '/admin/timetable'
    | '/admin/users'
    | '/discipline-master/attendance'
    | '/discipline-master/cases'
    | '/discipline-master/deduct-marks'
    | '/discipline-master/discipline'
    | '/discipline-master/messages'
    | '/discipline-master/notifications'
    | '/discipline-master/permission'
    | '/discipline-master/reports'
    | '/discipline-master/settings'
    | '/discipline-master/students'
    | '/parent/academic'
    | '/parent/attendance'
    | '/parent/children'
    | '/parent/discipline'
    | '/parent/messages'
    | '/parent/notifications'
    | '/parent/performance'
    | '/parent/reports'
    | '/student/attendance'
    | '/student/grades'
    | '/student/live'
    | '/student/materials'
    | '/student/quiz'
    | '/student/schedule'
    | '/teacher/attendance'
    | '/teacher/live'
    | '/teacher/marks'
    | '/teacher/materials'
    | '/teacher/messages'
    | '/teacher/reports'
    | '/admin'
    | '/discipline-master'
    | '/parent'
    | '/student'
    | '/teacher'
    | '/admin/teachers/$id'
    | '/admin/users/teacher'
    | '/discipline-master/deduct-marks/$id'
    | '/discipline-master/deduct-marks/test'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard-with-sidebar'
    | '/description'
    | '/discipline-master'
    | '/filter-page'
    | '/login'
    | '/login-parent'
    | '/login-staff'
    | '/login-student'
    | '/maintenance'
    | '/parent'
    | '/register-parent'
    | '/registration'
    | '/setup'
    | '/staff-dashboard'
    | '/staff-login'
    | '/staff-registration'
    | '/student'
    | '/student-dashboard'
    | '/teacher'
    | '/teacher-profile'
    | '/view-marks'
    | '/admin/academics'
    | '/admin/academics-backup'
    | '/admin/add-student'
    | '/admin/add-teacher'
    | '/admin/assign-classes'
    | '/admin/audit'
    | '/admin/deduct-marks'
    | '/admin/edit-teacher'
    | '/admin/manage-academics'
    | '/admin/manage-courses'
    | '/admin/notifications'
    | '/admin/parent-requests'
    | '/admin/previous-terms'
    | '/admin/reports'
    | '/admin/reset-password'
    | '/admin/send-notification'
    | '/admin/settings'
    | '/admin/student-discipline'
    | '/admin/students'
    | '/admin/teacher-info'
    | '/admin/teacher-profile'
    | '/admin/teachers'
    | '/admin/term-management'
    | '/admin/timetable'
    | '/admin/users'
    | '/discipline-master/attendance'
    | '/discipline-master/cases'
    | '/discipline-master/deduct-marks'
    | '/discipline-master/discipline'
    | '/discipline-master/messages'
    | '/discipline-master/notifications'
    | '/discipline-master/permission'
    | '/discipline-master/reports'
    | '/discipline-master/settings'
    | '/discipline-master/students'
    | '/parent/academic'
    | '/parent/attendance'
    | '/parent/children'
    | '/parent/discipline'
    | '/parent/messages'
    | '/parent/notifications'
    | '/parent/performance'
    | '/parent/reports'
    | '/student/attendance'
    | '/student/grades'
    | '/student/live'
    | '/student/materials'
    | '/student/quiz'
    | '/student/schedule'
    | '/teacher/attendance'
    | '/teacher/live'
    | '/teacher/marks'
    | '/teacher/materials'
    | '/teacher/messages'
    | '/teacher/reports'
    | '/admin/'
    | '/discipline-master/'
    | '/parent/'
    | '/student/'
    | '/teacher/'
    | '/admin/teachers/$id'
    | '/admin/users/teacher'
    | '/discipline-master/deduct-marks/$id'
    | '/discipline-master/deduct-marks/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardWithSidebarRoute: typeof DashboardWithSidebarRoute
  DescriptionRoute: typeof DescriptionRoute
  DisciplineMasterRoute: typeof DisciplineMasterRouteWithChildren
  FilterPageRoute: typeof FilterPageRoute
  LoginRoute: typeof LoginRoute
  LoginParentRoute: typeof LoginParentRoute
  LoginStaffRoute: typeof LoginStaffRoute
  LoginStudentRoute: typeof LoginStudentRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ParentRoute: typeof ParentRouteWithChildren
  RegisterParentRoute: typeof RegisterParentRoute
  RegistrationRoute: typeof RegistrationRoute
  SetupRoute: typeof SetupRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffLoginRoute: typeof StaffLoginRoute
  StaffRegistrationRoute: typeof StaffRegistrationRoute
  StudentRoute: typeof StudentRouteWithChildren
  StudentDashboardRoute: typeof StudentDashboardRoute
  TeacherRoute: typeof TeacherRouteWithChildren
  TeacherProfileRoute: typeof TeacherProfileRoute
  ViewMarksRoute: typeof ViewMarksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/view-marks': {
      id: '/view-marks'
      path: '/view-marks'
      fullPath: '/view-marks'
      preLoaderRoute: typeof ViewMarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-profile': {
      id: '/teacher-profile'
      path: '/teacher-profile'
      fullPath: '/teacher-profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-dashboard': {
      id: '/student-dashboard'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-registration': {
      id: '/staff-registration'
      path: '/staff-registration'
      fullPath: '/staff-registration'
      preLoaderRoute: typeof StaffRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-login': {
      id: '/staff-login'
      path: '/staff-login'
      fullPath: '/staff-login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-dashboard': {
      id: '/staff-dashboard'
      path: '/staff-dashboard'
      fullPath: '/staff-dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-parent': {
      id: '/register-parent'
      path: '/register-parent'
      fullPath: '/register-parent'
      preLoaderRoute: typeof RegisterParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-student': {
      id: '/login-student'
      path: '/login-student'
      fullPath: '/login-student'
      preLoaderRoute: typeof LoginStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-staff': {
      id: '/login-staff'
      path: '/login-staff'
      fullPath: '/login-staff'
      preLoaderRoute: typeof LoginStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-parent': {
      id: '/login-parent'
      path: '/login-parent'
      fullPath: '/login-parent'
      preLoaderRoute: typeof LoginParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filter-page': {
      id: '/filter-page'
      path: '/filter-page'
      fullPath: '/filter-page'
      preLoaderRoute: typeof FilterPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discipline-master': {
      id: '/discipline-master'
      path: '/discipline-master'
      fullPath: '/discipline-master'
      preLoaderRoute: typeof DisciplineMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/description': {
      id: '/description'
      path: '/description'
      fullPath: '/description'
      preLoaderRoute: typeof DescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-with-sidebar': {
      id: '/dashboard-with-sidebar'
      path: '/dashboard-with-sidebar'
      fullPath: '/dashboard-with-sidebar'
      preLoaderRoute: typeof DashboardWithSidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/discipline-master/': {
      id: '/discipline-master/'
      path: '/'
      fullPath: '/discipline-master/'
      preLoaderRoute: typeof DisciplineMasterIndexRouteImport
      parentRoute: typeof DisciplineMasterRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/reports': {
      id: '/teacher/reports'
      path: '/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/messages': {
      id: '/teacher/messages'
      path: '/messages'
      fullPath: '/teacher/messages'
      preLoaderRoute: typeof TeacherMessagesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/materials': {
      id: '/teacher/materials'
      path: '/materials'
      fullPath: '/teacher/materials'
      preLoaderRoute: typeof TeacherMaterialsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/marks': {
      id: '/teacher/marks'
      path: '/marks'
      fullPath: '/teacher/marks'
      preLoaderRoute: typeof TeacherMarksRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/live': {
      id: '/teacher/live'
      path: '/live'
      fullPath: '/teacher/live'
      preLoaderRoute: typeof TeacherLiveRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/schedule': {
      id: '/student/schedule'
      path: '/schedule'
      fullPath: '/student/schedule'
      preLoaderRoute: typeof StudentScheduleRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/quiz': {
      id: '/student/quiz'
      path: '/quiz'
      fullPath: '/student/quiz'
      preLoaderRoute: typeof StudentQuizRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/materials': {
      id: '/student/materials'
      path: '/materials'
      fullPath: '/student/materials'
      preLoaderRoute: typeof StudentMaterialsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/live': {
      id: '/student/live'
      path: '/live'
      fullPath: '/student/live'
      preLoaderRoute: typeof StudentLiveRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/grades': {
      id: '/student/grades'
      path: '/grades'
      fullPath: '/student/grades'
      preLoaderRoute: typeof StudentGradesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/parent/reports': {
      id: '/parent/reports'
      path: '/reports'
      fullPath: '/parent/reports'
      preLoaderRoute: typeof ParentReportsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/performance': {
      id: '/parent/performance'
      path: '/performance'
      fullPath: '/parent/performance'
      preLoaderRoute: typeof ParentPerformanceRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/notifications': {
      id: '/parent/notifications'
      path: '/notifications'
      fullPath: '/parent/notifications'
      preLoaderRoute: typeof ParentNotificationsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/messages': {
      id: '/parent/messages'
      path: '/messages'
      fullPath: '/parent/messages'
      preLoaderRoute: typeof ParentMessagesRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/discipline': {
      id: '/parent/discipline'
      path: '/discipline'
      fullPath: '/parent/discipline'
      preLoaderRoute: typeof ParentDisciplineRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/children': {
      id: '/parent/children'
      path: '/children'
      fullPath: '/parent/children'
      preLoaderRoute: typeof ParentChildrenRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/attendance': {
      id: '/parent/attendance'
      path: '/attendance'
      fullPath: '/parent/attendance'
      preLoaderRoute: typeof ParentAttendanceRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/academic': {
      id: '/parent/academic'
      path: '/academic'
      fullPath: '/parent/academic'
      preLoaderRoute: typeof ParentAcademicRouteImport
      parentRoute: typeof ParentRoute
    }
    '/discipline-master/students': {
      id: '/discipline-master/students'
      path: '/students'
      fullPath: '/discipline-master/students'
      preLoaderRoute: typeof DisciplineMasterStudentsRouteImport
      parentRoute: typeof DisciplineMasterRoute
    }
    '/discipline-master/settings': {
      id: '/discipline-master/settings'
      path: '/settings'
      fullPath: '/discipline-master/settings'
      preLoaderRoute: typeof DisciplineMasterSettingsRouteImport
      parentRoute: typeof DisciplineMasterRoute
    }
    '/discipline-master/reports': {
      id: '/discipline-master/reports'
      path: '/reports'
      fullPath: '/discipline-master/reports'
      preLoaderRoute: typeof DisciplineMasterReportsRouteImport
      parentRoute: typeof DisciplineMasterRoute
    }
    '/discipline-master/permission': {
      id: '/discipline-master/permission'
      path: '/permission'
      fullPath: '/discipline-master/permission'
      preLoaderRoute: typeof DisciplineMasterPermissionRouteImport
      parentRoute: typeof DisciplineMasterRoute
    }
    '/discipline-master/notifications': {
      id: '/discipline-master/notifications'
      path: '/notifications'
      fullPath: '/discipline-master/notifications'
      preLoaderRoute: typeof DisciplineMasterNotificationsRouteImport
      parentRoute: typeof DisciplineMasterRoute
    }
    '/discipline-master/messages': {
      id: '/discipline-master/messages'
      path: '/messages'
      fullPath: '/discipline-master/messages'
      preLoaderRoute: typeof DisciplineMasterMessagesRouteImport
      parentRoute: typeof DisciplineMasterRoute
    }
    '/discipline-master/discipline': {
      id: '/discipline-master/discipline'
      path: '/discipline'
      fullPath: '/discipline-master/discipline'
      preLoaderRoute: typeof DisciplineMasterDisciplineRouteImport
      parentRoute: typeof DisciplineMasterRoute
    }
    '/discipline-master/deduct-marks': {
      id: '/discipline-master/deduct-marks'
      path: '/deduct-marks'
      fullPath: '/discipline-master/deduct-marks'
      preLoaderRoute: typeof DisciplineMasterDeductMarksRouteImport
      parentRoute: typeof DisciplineMasterRoute
    }
    '/discipline-master/cases': {
      id: '/discipline-master/cases'
      path: '/cases'
      fullPath: '/discipline-master/cases'
      preLoaderRoute: typeof DisciplineMasterCasesRouteImport
      parentRoute: typeof DisciplineMasterRoute
    }
    '/discipline-master/attendance': {
      id: '/discipline-master/attendance'
      path: '/attendance'
      fullPath: '/discipline-master/attendance'
      preLoaderRoute: typeof DisciplineMasterAttendanceRouteImport
      parentRoute: typeof DisciplineMasterRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/timetable': {
      id: '/admin/timetable'
      path: '/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AdminTimetableRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/term-management': {
      id: '/admin/term-management'
      path: '/term-management'
      fullPath: '/admin/term-management'
      preLoaderRoute: typeof AdminTermManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teacher-profile': {
      id: '/admin/teacher-profile'
      path: '/teacher-profile'
      fullPath: '/admin/teacher-profile'
      preLoaderRoute: typeof AdminTeacherProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teacher-info': {
      id: '/admin/teacher-info'
      path: '/teacher-info'
      fullPath: '/admin/teacher-info'
      preLoaderRoute: typeof AdminTeacherInfoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/student-discipline': {
      id: '/admin/student-discipline'
      path: '/student-discipline'
      fullPath: '/admin/student-discipline'
      preLoaderRoute: typeof AdminStudentDisciplineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/send-notification': {
      id: '/admin/send-notification'
      path: '/send-notification'
      fullPath: '/admin/send-notification'
      preLoaderRoute: typeof AdminSendNotificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/previous-terms': {
      id: '/admin/previous-terms'
      path: '/previous-terms'
      fullPath: '/admin/previous-terms'
      preLoaderRoute: typeof AdminPreviousTermsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parent-requests': {
      id: '/admin/parent-requests'
      path: '/parent-requests'
      fullPath: '/admin/parent-requests'
      preLoaderRoute: typeof AdminParentRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage-courses': {
      id: '/admin/manage-courses'
      path: '/manage-courses'
      fullPath: '/admin/manage-courses'
      preLoaderRoute: typeof AdminManageCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage-academics': {
      id: '/admin/manage-academics'
      path: '/manage-academics'
      fullPath: '/admin/manage-academics'
      preLoaderRoute: typeof AdminManageAcademicsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/edit-teacher': {
      id: '/admin/edit-teacher'
      path: '/edit-teacher'
      fullPath: '/admin/edit-teacher'
      preLoaderRoute: typeof AdminEditTeacherRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deduct-marks': {
      id: '/admin/deduct-marks'
      path: '/deduct-marks'
      fullPath: '/admin/deduct-marks'
      preLoaderRoute: typeof AdminDeductMarksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assign-classes': {
      id: '/admin/assign-classes'
      path: '/assign-classes'
      fullPath: '/admin/assign-classes'
      preLoaderRoute: typeof AdminAssignClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/add-teacher': {
      id: '/admin/add-teacher'
      path: '/add-teacher'
      fullPath: '/admin/add-teacher'
      preLoaderRoute: typeof AdminAddTeacherRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/add-student': {
      id: '/admin/add-student'
      path: '/add-student'
      fullPath: '/admin/add-student'
      preLoaderRoute: typeof AdminAddStudentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academics-backup': {
      id: '/admin/academics-backup'
      path: '/academics-backup'
      fullPath: '/admin/academics-backup'
      preLoaderRoute: typeof AdminAcademicsBackupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academics': {
      id: '/admin/academics'
      path: '/academics'
      fullPath: '/admin/academics'
      preLoaderRoute: typeof AdminAcademicsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/discipline-master/deduct-marks/test': {
      id: '/discipline-master/deduct-marks/test'
      path: '/test'
      fullPath: '/discipline-master/deduct-marks/test'
      preLoaderRoute: typeof DisciplineMasterDeductMarksTestRouteImport
      parentRoute: typeof DisciplineMasterDeductMarksRoute
    }
    '/discipline-master/deduct-marks/$id': {
      id: '/discipline-master/deduct-marks/$id'
      path: '/$id'
      fullPath: '/discipline-master/deduct-marks/$id'
      preLoaderRoute: typeof DisciplineMasterDeductMarksIdRouteImport
      parentRoute: typeof DisciplineMasterDeductMarksRoute
    }
    '/admin/users/teacher': {
      id: '/admin/users/teacher'
      path: '/teacher'
      fullPath: '/admin/users/teacher'
      preLoaderRoute: typeof AdminUsersTeacherRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/teachers/$id': {
      id: '/admin/teachers/$id'
      path: '/$id'
      fullPath: '/admin/teachers/$id'
      preLoaderRoute: typeof AdminTeachersIdRouteImport
      parentRoute: typeof AdminTeachersRoute
    }
  }
}

interface AdminTeachersRouteChildren {
  AdminTeachersIdRoute: typeof AdminTeachersIdRoute
}

const AdminTeachersRouteChildren: AdminTeachersRouteChildren = {
  AdminTeachersIdRoute: AdminTeachersIdRoute,
}

const AdminTeachersRouteWithChildren = AdminTeachersRoute._addFileChildren(
  AdminTeachersRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersTeacherRoute: typeof AdminUsersTeacherRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersTeacherRoute: AdminUsersTeacherRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAcademicsRoute: typeof AdminAcademicsRoute
  AdminAcademicsBackupRoute: typeof AdminAcademicsBackupRoute
  AdminAddStudentRoute: typeof AdminAddStudentRoute
  AdminAddTeacherRoute: typeof AdminAddTeacherRoute
  AdminAssignClassesRoute: typeof AdminAssignClassesRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDeductMarksRoute: typeof AdminDeductMarksRoute
  AdminEditTeacherRoute: typeof AdminEditTeacherRoute
  AdminManageAcademicsRoute: typeof AdminManageAcademicsRoute
  AdminManageCoursesRoute: typeof AdminManageCoursesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminParentRequestsRoute: typeof AdminParentRequestsRoute
  AdminPreviousTermsRoute: typeof AdminPreviousTermsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSendNotificationRoute: typeof AdminSendNotificationRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentDisciplineRoute: typeof AdminStudentDisciplineRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeacherInfoRoute: typeof AdminTeacherInfoRoute
  AdminTeacherProfileRoute: typeof AdminTeacherProfileRoute
  AdminTeachersRoute: typeof AdminTeachersRouteWithChildren
  AdminTermManagementRoute: typeof AdminTermManagementRoute
  AdminTimetableRoute: typeof AdminTimetableRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcademicsRoute: AdminAcademicsRoute,
  AdminAcademicsBackupRoute: AdminAcademicsBackupRoute,
  AdminAddStudentRoute: AdminAddStudentRoute,
  AdminAddTeacherRoute: AdminAddTeacherRoute,
  AdminAssignClassesRoute: AdminAssignClassesRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDeductMarksRoute: AdminDeductMarksRoute,
  AdminEditTeacherRoute: AdminEditTeacherRoute,
  AdminManageAcademicsRoute: AdminManageAcademicsRoute,
  AdminManageCoursesRoute: AdminManageCoursesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminParentRequestsRoute: AdminParentRequestsRoute,
  AdminPreviousTermsRoute: AdminPreviousTermsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSendNotificationRoute: AdminSendNotificationRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentDisciplineRoute: AdminStudentDisciplineRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeacherInfoRoute: AdminTeacherInfoRoute,
  AdminTeacherProfileRoute: AdminTeacherProfileRoute,
  AdminTeachersRoute: AdminTeachersRouteWithChildren,
  AdminTermManagementRoute: AdminTermManagementRoute,
  AdminTimetableRoute: AdminTimetableRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DisciplineMasterDeductMarksRouteChildren {
  DisciplineMasterDeductMarksIdRoute: typeof DisciplineMasterDeductMarksIdRoute
  DisciplineMasterDeductMarksTestRoute: typeof DisciplineMasterDeductMarksTestRoute
}

const DisciplineMasterDeductMarksRouteChildren: DisciplineMasterDeductMarksRouteChildren =
  {
    DisciplineMasterDeductMarksIdRoute: DisciplineMasterDeductMarksIdRoute,
    DisciplineMasterDeductMarksTestRoute: DisciplineMasterDeductMarksTestRoute,
  }

const DisciplineMasterDeductMarksRouteWithChildren =
  DisciplineMasterDeductMarksRoute._addFileChildren(
    DisciplineMasterDeductMarksRouteChildren,
  )

interface DisciplineMasterRouteChildren {
  DisciplineMasterAttendanceRoute: typeof DisciplineMasterAttendanceRoute
  DisciplineMasterCasesRoute: typeof DisciplineMasterCasesRoute
  DisciplineMasterDeductMarksRoute: typeof DisciplineMasterDeductMarksRouteWithChildren
  DisciplineMasterDisciplineRoute: typeof DisciplineMasterDisciplineRoute
  DisciplineMasterMessagesRoute: typeof DisciplineMasterMessagesRoute
  DisciplineMasterNotificationsRoute: typeof DisciplineMasterNotificationsRoute
  DisciplineMasterPermissionRoute: typeof DisciplineMasterPermissionRoute
  DisciplineMasterReportsRoute: typeof DisciplineMasterReportsRoute
  DisciplineMasterSettingsRoute: typeof DisciplineMasterSettingsRoute
  DisciplineMasterStudentsRoute: typeof DisciplineMasterStudentsRoute
  DisciplineMasterIndexRoute: typeof DisciplineMasterIndexRoute
}

const DisciplineMasterRouteChildren: DisciplineMasterRouteChildren = {
  DisciplineMasterAttendanceRoute: DisciplineMasterAttendanceRoute,
  DisciplineMasterCasesRoute: DisciplineMasterCasesRoute,
  DisciplineMasterDeductMarksRoute:
    DisciplineMasterDeductMarksRouteWithChildren,
  DisciplineMasterDisciplineRoute: DisciplineMasterDisciplineRoute,
  DisciplineMasterMessagesRoute: DisciplineMasterMessagesRoute,
  DisciplineMasterNotificationsRoute: DisciplineMasterNotificationsRoute,
  DisciplineMasterPermissionRoute: DisciplineMasterPermissionRoute,
  DisciplineMasterReportsRoute: DisciplineMasterReportsRoute,
  DisciplineMasterSettingsRoute: DisciplineMasterSettingsRoute,
  DisciplineMasterStudentsRoute: DisciplineMasterStudentsRoute,
  DisciplineMasterIndexRoute: DisciplineMasterIndexRoute,
}

const DisciplineMasterRouteWithChildren =
  DisciplineMasterRoute._addFileChildren(DisciplineMasterRouteChildren)

interface ParentRouteChildren {
  ParentAcademicRoute: typeof ParentAcademicRoute
  ParentAttendanceRoute: typeof ParentAttendanceRoute
  ParentChildrenRoute: typeof ParentChildrenRoute
  ParentDisciplineRoute: typeof ParentDisciplineRoute
  ParentMessagesRoute: typeof ParentMessagesRoute
  ParentNotificationsRoute: typeof ParentNotificationsRoute
  ParentPerformanceRoute: typeof ParentPerformanceRoute
  ParentReportsRoute: typeof ParentReportsRoute
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentAcademicRoute: ParentAcademicRoute,
  ParentAttendanceRoute: ParentAttendanceRoute,
  ParentChildrenRoute: ParentChildrenRoute,
  ParentDisciplineRoute: ParentDisciplineRoute,
  ParentMessagesRoute: ParentMessagesRoute,
  ParentNotificationsRoute: ParentNotificationsRoute,
  ParentPerformanceRoute: ParentPerformanceRoute,
  ParentReportsRoute: ParentReportsRoute,
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface StudentRouteChildren {
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentGradesRoute: typeof StudentGradesRoute
  StudentLiveRoute: typeof StudentLiveRoute
  StudentMaterialsRoute: typeof StudentMaterialsRoute
  StudentQuizRoute: typeof StudentQuizRoute
  StudentScheduleRoute: typeof StudentScheduleRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentGradesRoute: StudentGradesRoute,
  StudentLiveRoute: StudentLiveRoute,
  StudentMaterialsRoute: StudentMaterialsRoute,
  StudentQuizRoute: StudentQuizRoute,
  StudentScheduleRoute: StudentScheduleRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherLiveRoute: typeof TeacherLiveRoute
  TeacherMarksRoute: typeof TeacherMarksRoute
  TeacherMaterialsRoute: typeof TeacherMaterialsRoute
  TeacherMessagesRoute: typeof TeacherMessagesRoute
  TeacherReportsRoute: typeof TeacherReportsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherLiveRoute: TeacherLiveRoute,
  TeacherMarksRoute: TeacherMarksRoute,
  TeacherMaterialsRoute: TeacherMaterialsRoute,
  TeacherMessagesRoute: TeacherMessagesRoute,
  TeacherReportsRoute: TeacherReportsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardWithSidebarRoute: DashboardWithSidebarRoute,
  DescriptionRoute: DescriptionRoute,
  DisciplineMasterRoute: DisciplineMasterRouteWithChildren,
  FilterPageRoute: FilterPageRoute,
  LoginRoute: LoginRoute,
  LoginParentRoute: LoginParentRoute,
  LoginStaffRoute: LoginStaffRoute,
  LoginStudentRoute: LoginStudentRoute,
  MaintenanceRoute: MaintenanceRoute,
  ParentRoute: ParentRouteWithChildren,
  RegisterParentRoute: RegisterParentRoute,
  RegistrationRoute: RegistrationRoute,
  SetupRoute: SetupRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffLoginRoute: StaffLoginRoute,
  StaffRegistrationRoute: StaffRegistrationRoute,
  StudentRoute: StudentRouteWithChildren,
  StudentDashboardRoute: StudentDashboardRoute,
  TeacherRoute: TeacherRouteWithChildren,
  TeacherProfileRoute: TeacherProfileRoute,
  ViewMarksRoute: ViewMarksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
